# gruvbox-material.toml
base = "ocean"
syntax = "base16-ocean.dark"

[ui]
toc_bg = "#1b1b1b"
toc_border = "#45403d"
content_bg = "#282828"
scrollbar_hover = "#d8a657"
status_bg = "#1b1b1b"
status_separator = "#928374"
status_brand_fg = "#282828"
status_brand_bg = "#d8a657"
status_filename_fg = "#d4be98"
status_filename_bg = "#32302f"
status_watch_fg = "#a9b665"
status_watch_bg = "#34381b"
status_reloaded_fg = "#282828"
status_reloaded_bg = "#a9b665"
status_search_fg = "#d8a657"
status_search_bg = "#32302f"
status_success_fg = "#a9b665"
status_success_bg = "#34381b"
status_warning_fg = "#d8a657"
status_error_fg = "#ea6962"
status_error_bg = "#402120"
status_shortcut_fg = "#928374"
status_percent_fg = "#d8a657"
status_dot_fg = "#928374"
toc_hover_fg = "#ddc7a1"
toc_header_fg = "#928374"
toc_active_bg = "#32302f"
toc_inactive_bg = "#1b1b1b"
toc_accent = "#e78a4e"
toc_index_inactive = "#7c6f64"
toc_primary_active = "#ddc7a1"
toc_primary_inactive = "#d4be98"
toc_secondary_inactive = "#7c6f64"
toc_secondary_text_active = "#d4be98"
toc_secondary_text_inactive = "#928374"

[markdown]
search_highlight_bg = "#45403d"
search_match_bg = "#d8a657"
code_gutter = "#7c6f64"
blockquote_marker = "#928374"
list_level_1 = "#a9b665"
list_level_2 = "#7daea3"
list_level_3 = "#d3869b"
ordered_list = "#d8a657"
table_border = "#5a524c"
table_separator = "#45403d"
table_header = "#d8a657"
table_cell = "#d4be98"
heading_1 = "#ea6962"
heading_2 = "#e78a4e"
heading_3 = "#d8a657"
heading_4 = "#a9b665"
heading_other = "#e78a4e"
heading_underline = "#45403d"
code_frame = "#5a524c"
code_label = "#928374"
inline_code_fg = "#e78a4e"
inline_code_bg = "#32302f"
rule = "#45403d"
link_icon = "#7daea3"
link_text = "#7daea3"
link_hover = "#89b482"
blockquote_text = "#d4be98"
text = "#d4be98"
strong_text = "#ddc7a1"
latex_inline_fg = "#d3869b"
latex_inline_bg = "#32302f"
latex_block_fg = "#d3869b"
mermaid_keyword = "#e78a4e"
mermaid_arrow = "#7daea3"
mermaid_label = "#a9b665"
mermaid_block_fg = "#d4be98"
mark_fg = "#ddc7a1"
mark_bg = "#4f422e"
task_checked = "#a9b665"
task_unchecked = "#928374"
alert_note = "#7daea3"
alert_tip = "#a9b665"
alert_important = "#d3869b"
alert_warning = "#d8a657"
alert_caution = "#ea6962"
footnote_ref = "#7daea3"
footnote_text = "#d4be98"

[diff]
file_separator_fg = "#d4be98"
tree_tag_change = "#e78a4e"
tree_tag_renamed = "#7daea3"

[theme]
transparent_bg = true
