# Hydrogen

spacing         = 2
padding         = 2
hide_ascii      = false
separator       = ">"
key_color       = "Yellow"
separator_color = "Green"

[palette]
type = "Full"
visible = false

[bar]
glyph           = "o"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
border          = "rounded"
visible         = false

[box.inner_margin]
x               = 5
y               = 3

[custom_ascii]
color = "Magenta"
path = "~/.config/macchina/themes/img.txt"

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "Local IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
gpu             = "GPU"
disk_space      = "Disk Space"
