# Cursor Dark
[colors]
foreground = "#ffffff"
background = "#141414"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#141414"
selection_bg = "#303030"
selection_fg = "#ffffff"

ansi = ["#2a2a2a","#bf616a","#a3be8c","#ebcb8b","#81a1c1","#b48ead","#88c0d0","#d8dee9"]
brights = ["#505050","#bf616a","#a3be8c","#ebcb8b","#81a1c1","#b48ead","#88c0d0","#ffffff"]
